package com.portalcursos.ng02.model;

public enum EDocumentType {
    RG, 
    CPF, 
    TITULO_ELEITOR, 
    CERTIFICADO_RESERVISTA, 
    CERTIDAO_NASCIMENTO, 
    COMPROVANTE_RESIDENCIA, 
    FOTO_3X4, 
    CERTIFICADO_EM, 
    HISTORICO_EM, 
    DIPLOMA_ANT, 
    DECLARACAO_AUT_IES, 
    DECLARACAO_MAT_IES_ANT, 
    HISTORICO_IES_ANT, 
    RNM_RNE, 
    PROVA_REVALIDACAO_EM, 
    LAUDO_MEDICO,
    AUTODECLARACAO_RACIAL, 
    COMPROVANTE_RENDA,
    ENEM_SISU,
    DIPLOMA,
    HISTORICO_ESCOLAR
}
