-- Configuração única do plano (linha id=1): quando o ciclo semanal reseta e qual o orçamento.
CREATE TABLE token_plan_config (
    id                  SMALLINT PRIMARY KEY,
    plan_name           VARCHAR(40)  NOT NULL,
    reset_day_of_week   SMALLINT     NOT NULL,
    reset_time          TIME         NOT NULL,
    timezone            VARCHAR(60)  NOT NULL,
    weekly_limit_tokens BIGINT       NOT NULL,
    count_cache_reads   BOOLEAN      NOT NULL DEFAULT FALSE,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT ck_plan_config_singleton CHECK (id = 1),
    CONSTRAINT ck_plan_config_day CHECK (reset_day_of_week BETWEEN 1 AND 7),
    CONSTRAINT ck_plan_config_limit CHECK (weekly_limit_tokens > 0)
);

-- Valores iniciais são PLACEHOLDERS: a Anthropic não publica o limite semanal exato.
-- Ajuste via PUT /api/tokens/config (tela de configuração do dashboard).
INSERT INTO token_plan_config
    (id, plan_name, reset_day_of_week, reset_time, timezone, weekly_limit_tokens, count_cache_reads, updated_at)
VALUES (1, 'Claude Code Pro', 1, '00:00:00', 'America/Sao_Paulo', 50000000, FALSE, CURRENT_TIMESTAMP);

-- Uma linha por mensagem do assistente (usage de cada resposta). Só contagens e metadados — sem conteúdo.
CREATE TABLE token_usage_entries (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id            VARCHAR(128) NOT NULL,
    occurred_at           TIMESTAMP WITH TIME ZONE NOT NULL,
    hour_bucket           TIMESTAMP WITH TIME ZONE NOT NULL,
    session_id            VARCHAR(64),
    process               VARCHAR(120) NOT NULL,
    model                 VARCHAR(80)  NOT NULL,
    input_tokens          BIGINT NOT NULL DEFAULT 0,
    output_tokens         BIGINT NOT NULL DEFAULT 0,
    cache_creation_tokens BIGINT NOT NULL DEFAULT 0,
    cache_read_tokens     BIGINT NOT NULL DEFAULT 0,
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_usage_message UNIQUE (message_id),
    CONSTRAINT ck_usage_non_negative CHECK (
        input_tokens >= 0 AND output_tokens >= 0 AND cache_creation_tokens >= 0 AND cache_read_tokens >= 0)
);

CREATE INDEX idx_usage_occurred_at ON token_usage_entries (occurred_at);
CREATE INDEX idx_usage_process_occurred ON token_usage_entries (process, occurred_at);
